name: Check

on: [push, pull_request]

jobs:
    run-ls:
        name: ${{ matrix.gnat }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-24.04, ubuntu-24.04-arm]
                gnat: [gnat-10, gnat-11, gnat-12, gnat]
            fail-fast: false

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: true

            - name: Set up GNAT
              run: sudo apt-get update && sudo apt-get install -y ${{ matrix.gnat }} gprbuild

            - name: Run
              run: |
                  echo "Using GNAT: $(gnat --version)"
                  gprbuild
                  ./bin/bug_bigfloat_adatoml